### ISSUE TITLE
MS Teams compatibility

### ISSUE THREAD

**Issue by mosajjal** [BountyStrike/Emissary#1]
Hi,

Microsoft Teams channels use webhook URL and have a basic syntax. Any plans to add it to this project? 

Thanks :)

**Comment by mjdubell** [comment]
Haven't thought about it but it sounds like a good idea, I will add it to my list :)

**Comment by mjdubell** [comment]
Fixed in https://github.com/BountyStrike/Emissary/pull/2

**Comment by mjdubell** [comment]
Released here: https://github.com/BountyStrike/Emissary/releases/tag/v0.8.5
