### ISSUE TITLE
Discord webhook not working

### ISSUE THREAD

**Issue by wellenc-lex** [BountyStrike/Emissary#23]
Hello, dubs3c! I'm running emissary like that but getting 400 response with discord, am I doing something wrong?
 
```
 emissary -in "webhook:=https://discord.com/api/webhooks/1098611499406196766/--CNYWGVsQDL5HMrjf3nok3XifJ_0oV6-0§textField:=content" -m "It works!" 
2023/08/05 23:35:30 Error reading response body: http2: response body closed
2023/08/05 23:35:30 Response HTTP Status code:  400
2023/08/05 23:35:30 Response HTTP Body:  
```

**Comment by dubs3c** [comment]
Looking into it. But you should probably remove your webhook :)

**Comment by dubs3c** [comment]
Found the issue, although I'm not sure why this is not working any longer. In any case, the code requires some heavy refactoring, can't believe I written this code...

Your best bet is to try using config files in the mean time.
