### ISSUE TITLE
limit line sent 

### ISSUE THREAD

**Issue by ahmed1231230** [BountyStrike/Emissary#3]
Hello
There are only 20 lines left
Is it possible to send more than that?

**Comment by dubs3c** [comment]
$ emissary
Send data through chat channels. Made by @dubs3c.

Usage:
  emissary [channel] [message]

Options:
  -s,  --slack        Send via Slack
  -t,  --telegram     Send via Telegram
  -e,  --email        Send via Email
  -ms, --teams        Send via Microsoft Teams
  -si, --stdin        Get message from stdin
  -m,  --message      Message to send
  **-r,  --rows         Max rows/lines to send, 0 for unlimited. Default 20**
  -v,  --version      Show version

Examples:
  emissary -telegram --message "Hello telegram"
  cat domins.txt | emissary --slack --stdin
