### ISSUE TITLE
Many webhook 

### ISSUE THREAD

**Issue by alanEG** [BountyStrike/Emissary#4]
hello 
Several web hook can be customized
For multiple uses
Example if you want to send a message to Group A
Next, send a message to Group B.
This will require changing the webhook variable in the second message

**Comment by dubs3c** [comment]
Do you mean you want to be able to send to multiple webhooks just be specifying each url?

**Comment by ahmed1231230** [comment]
hello @dubs3c 

Yes, that's what I mean

**Comment by dubs3c** [comment]
Alright, that sounds like it should be pretty easy to do. I'll try to update Emissary during the week to support this feature.

**Comment by dubs3c** [comment]
I am developing this feature now.

**Comment by dubs3c** [comment]
The program now supports this feature. However I made some breaking changes so make sure check README.md.

You can test by checking out this branch: https://github.com/BountyStrike/Emissary/tree/feature/Custom-Webhooks

**Comment by alanEG** [comment]
hello  @dubs3c
The function works great
I wish you success

**Comment by dubs3c** [comment]
This feature has been been implemented, merged and released in version 1.0.0 :) https://github.com/BountyStrike/Emissary/releases/tag/v1.0.0
