### ISSUE TITLE
Customizable Header Message

### ISSUE THREAD

**Issue by 0d4rujd** [BountyStrike/Emissary#8]
Hello, 

First of all thank you for such a great tool, it is really useful :)

I would like to know if it is possible to customize the first line "Data from Emissary". It would be great having like a --header flag where I can define my own message, for example: "New subdomains from $subdomain". 

This way, the first line of each message will include from which program the output cames from. 

Thanks in advance! 
Regards,

**Comment by dubs3c** [comment]
Hi, nice to know someone is using emissary 😄

It should be easy to implement what you suggest. I'll fix it 🙂

**Comment by 0d4rujd** [comment]
The tool is pretty cool :) Thank you for your quick response! 

I also was willing if there is an option to send a file instead of a message? In case of larger files, is very useful to send the conent in a file. This content is grouped by default and in case of very large files, you can click and it will be opened in a new tab. 
Maybe you can add another flag --file to send content as a file (is just an idea).

This is what I am looking for (including header and sending it as a file)
![image](https://user-images.githubusercontent.com/16767612/110205462-4abce200-7e78-11eb-8d00-4fb325fe971c.png)

Hope it helps and thanks for your awesome work.

**Comment by dubs3c** [comment]
Sending a file is not a bad idea, could be very useful. But I think it would depend on the receiver if they support. For example, Discord maybe would not support sending files while Slack would. But I can look into it :)

**Comment by 0d4rujd** [comment]
Thanks @dubs3c in case of slack it would be very useful. Not sure if discord or Telegram also support this..maybe not.

**Comment by dubs3c** [comment]
This feature was added here https://github.com/BountyStrike/Emissary/commit/d695654305e32a2f80d9a87fc97a7b183c4a7694 and released here https://github.com/BountyStrike/Emissary/tree/v1.1.0
